#!/bin/bash

###############################################################################
# This file is part of the swblocks-baselib library.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

###############################################################################
# Generate ci-init-env.mk for the build system
#
# This script creates projects/make/ci-init-env.mk inside the dist directory,
# setting DIST_ROOT_DEPS1/2/3 for the makefile build system.
#
# Usage: ./generate-ci-init-env.sh DIST_DIR_NAME
#   DIST_DIR_NAME: Full dist directory name (e.g. dist-devenv7-darwin-25-a64)
#
# The dist directory must exist at ${HOME}/swblocks/${DIST_DIR_NAME}
###############################################################################

set -e  # Exit on error
set -u  # Exit on undefined variable

DIST_DIR_NAME="${1:?ERROR: DIST_DIR_NAME is required}"
SWBLOCKS_ROOT="${HOME}/swblocks"
BASE_DIR="${SWBLOCKS_ROOT}/${DIST_DIR_NAME}"

if [ ! -d "${BASE_DIR}" ]; then
    echo "ERROR: Distribution directory not found: ${BASE_DIR}"
    exit 1
fi

# Create output directories
CI_DIR="${BASE_DIR}/scripts/ci"
MK_DIR="${BASE_DIR}/projects/make"
mkdir -p "${CI_DIR}"
mkdir -p "${MK_DIR}"

# Generate ci-init-env.mk
MK_FILE="${MK_DIR}/ci-init-env.mk"
cat > "${MK_FILE}" << EOF
# Initialize the important env roots
# Auto-generated by generate-ci-init-env.sh

DIST_ROOT_DEPS1 = \$(HOME)/swblocks/${DIST_DIR_NAME}
DIST_ROOT_DEPS2 = \$(HOME)/swblocks/${DIST_DIR_NAME}
DIST_ROOT_DEPS3 = \$(HOME)/swblocks/${DIST_DIR_NAME}
EOF

echo "Generated: ${MK_FILE}"
